"""
Django settings for VAST_DS project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os#, sys
#from bokeh.settings import bokehjs_path, settings as bokeh_settings
from bokeh.settings import settings as bokeh_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-95(dkg@8@7i#ar45)jctudjfdi=k%58ul1+$&)=53_8-mmh45$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['svvm0003.xaas.epfl.ch:8002','127.0.0.1', 'localhost:8002', '0.0.0.0:8002', 'sv-upoates.epfl.ch', 'localhost']

GRAPH_MODELS = {
  'all_applications': True,
  'group_models': True,
  'app_labels': ["VAST_DS"],
  }


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'well_mapping.apps.WellMappingConfig', 
    'channels',
    'bokeh_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'VAST_DS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'VAST_DS.asgi.application'
WSGI_APPLICATION = 'VAST_DS.wsgi.application'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240 # higher than the count of fields


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# default (Linux/macOS path)
DBPATH = Path('/Volumes/upoates/raw_data/microscopy/vast/vast_db')

# override if Windows path exists
win_path = Path(r'Y:\raw_data\microscopy\vast\vast_db')
if win_path.exists():
    DBPATH = win_path

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(DBPATH / 'db.sqlite3'),  # must be a string
    }
}




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

try:
    bokeh_js_dir = bokeh_settings.bokehjs_path()
except AttributeError:
    # support bokeh versions < 3.4
    bokeh_js_dir = bokeh_settings.bokehjsdir()

STATICFILES_DIRS = [
   os.path.join(BASE_DIR, "static"),

   bokeh_js_dir,
]

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    'bokeh_django.static.BokehExtensionFinder',
)

bokeh_settings.resources = 'server'